export const OccupationOptions = [
  "Student",
  "Healthcare Provider",
  "Working Abroad",
  "Govt. Employee",
  "Private Employee",
  "Homemaker/Housewife",
  "Others",
];

export const HealthCentreTypeOptions = [
  "Family Health Centres",
  "Educational Inst",
  "Private Hospital",
  "Other",
  "Hostel",
  "Hotel",
  "Lodge",
  "TeleMedicine",
  "Govt Hospital",
  "Primary Health Centres",
  "24x7 Public Health Centres",
  "Family Health Centres",
  "Community Health Centres",
  "Urban Primary Health Center",
  "Taluk Hospitals",
  "Taluk Headquarters Hospitals",
  "Women and Child Health Centres",
  "General hospitals",
  "District Hospitals",
];
